site_name: Frequently Asked Questions
site_url: https://tab1-web.github.io/faq/
  
extra_css:
  - stylesheets/extra.css
use_directory_urls: true 

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-6G22445Y9H
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
nav:
  - Home: index.md
  - Getting Started:
    - Welcome: getting-started/welcome.md
    - Server Information: getting-started/servers.md
  - Gameplay:
    - Core Mechanics: gameplay/core-mechanics.md
    - Controls: gameplay/controls.md
    - PvP System: gameplay/pvp-system.md
    - Monsters: gameplay/monsters.md
    - Seven Signs: gameplay/sevensigns.md
    - Buffs: gameplay/buffs.md
    - Dyes: gameplay/dyes.md
    - Macro: gameplay/macro.md
    - Abbrevations: gameplay/abbreviations.md
    - Donation: cosmetics/overview.md
    - Manor: gameplay/manor.md
    - Tools:
      - L2Calc (Character): features/l2calcinterlude.md
      - L2Calc (Summons): features/l2calcsum.md
      - C5+ Map: features/c5map.md
    - Character Progression:
      - Voting: gameplay/progression/voting.md
      - Achievements: gameplay/progression/achievements.md
      - Class Transfers: gameplay/progression/classtransfer.md
      - Subclasses: gameplay/progression/subclasses.md
      - Noblesse: gameplay/progression/noblesse.md
      - Heroes & Olympiad: gameplay/progression/heroes.md
    - Interface:
      - Shops: interface/shops.md
      - Colorful Chat: interface/systemmessage.md
      - Transferring Items: interface/transferring.md
  - Support:
    - Rules & Guidelines: support/rules.md
    - User Safety: support/user-safety.md
    - Reporting: support/reporting.md
    - Creating Tickets: support/tickets.md
    - Troubleshooting:
      - In-Game Issues: support/troubleshooting/game-issues.md
      - Out-of-Game Issues: support/troubleshooting/technical-issues.md
      - Account & Login Issues: support/login-issues.md
  - Eternal:
    - Eternal General: eternal/general.md
    - Maria: eternal/maria.md
    - Levelling: eternal/levelling.md
    - Classes: eternal/classes.md
    - Events: eternal/events.md
    - Missions: eternal/missions.md
    - Daily Login: eternal/dailyattendance.md
    - Augmenting: eternal/augmenting.md
    - Enchanting: eternal/enchanting.md
    - Bosses: eternal/bosses.md
    - Advanced Find Store: eternal/storefind.md
    - Fortune Wheel: eternal/fortunewheel.md
    - Eternal FAQ: eternal/faq.md
  - Signature:
    - Signature General: signature/general.md
    - Levelling Guide: signature/quests.md
    - FAQ: signature/faq.md
    - Cosmetic Preview:
      - signature/cosmetics/hats.md
      - signature/cosmetics/cloaks.md
      - signature/cosmetics/suits.md
      - signature/cosmetics/agathions.md
  - Essence:
    - OBT Fixes: essence/fixed_issues.md
    - Vanitasss' Experimentarium:
      - 001 Triple Shot Cooldown Reduction: essence/exp001.md
      - 002 Mystic Explosion Relic Cooldown Reduction: essence/exp002.md
      - 003 Essential Fatal Crush Cooldown Reduction: essence/exp003.md

  
theme:
  name: material
  
  icon:
    logo: material/frequently-asked-questions
  
  font:
    text: Poppins
    code: Red Hat Mono

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.path
    - content.code.copy
    - navigation.indexes
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.snippets
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - admonition

plugins:
  - search:
      lang: en