site_name: Frequently Asked Questions
site_url: https://tab1-web.github.io/faq/
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Getting Started:
    - Welcome: getting-started/welcome.md
    - Server Information: getting-started/servers.md
  - Gameplay:
    - Core Mechanics: gameplay/core-mechanics.md
    - Controls: gameplay/controls.md
    - PvP System: gameplay/pvp-system.md
    - Monsters: gameplay/monsters.md
    - Buffs: gameplay/buffs.md
    - Dyes: gameplay/dyes.md
    - Macro: gameplay/macro.md
    - Abbrevations: gameplay/abbreviations.md
    - Tools:
      - L2Calc (Character): features/l2calcinterlude.md
      - L2Calc (Summons): features/l2calcsum.md
      - Crafter: features/crafter.md
      - C5+ Map: features/c5map.md
    - Character Progression:
      - Voting: gameplay/progression/voting.md
      - Class Transfers: gameplay/progression/classtransfer.md
      - Subclasses: gameplay/progression/subclasses.md
      - Noblesse: gameplay/progression/noblesse.md
      - Heroes & Olympiad: gameplay/progression/heroes.md
    - Interface:
      - Shops: interface/shops.md
      - Colorful Chat: interface/systemmessage.md
      - Transferring Items: interface/transferring.md
  - Cosmetics:
    - Overview: cosmetics/overview.md
    - Hats: cosmetics/hats.md
    - Suits: cosmetics/suits.md
    - Cloaks: cosmetics/cloaks.md
    - Agathions: cosmetics/agathions.md
  - Support:
    - Rules & Guidelines: support/rules.md
    - User Safety: support/user-safety.md
    - Reporting: support/reporting.md
    - Creating Tickets: support/tickets.md
    - Troubleshooting:
      - In-Game Issues: support/troubleshooting/game-issues.md
      - Out-of-Game Issues: support/troubleshooting/technical-issues.md
      - Account & Login Issues: support/login-issues.md
  - Eternal:
    - General: eternal/general.md
    - Maria: eternal/maria.md
    - Levelling: eternal/levelling.md
    - Classes: eternal/classes.md
    - Events: eternal/events.md
    - Missions: eternal/missions.md
    - Daily Login: eternal/dailyattendance.md
    - Augmenting: eternal/augmenting.md
    - Enchanting: eternal/enchanting.md
    - Fortune Wheel: eternal/fortunewheel.md
    - FAQ: eternal/faq.md
  
theme:
  name: material
  
  
  icon:
    logo: material/frequently-asked-questions

  
  font:
    text: Poppins
    code: Red Hat Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.path
    - content.code.copy
    - navigation.indexes
  watch:
  - '!classtransfers/*.md'   # Ignores entire classtransfers folder
  - '!eternal/questexchanges/*.md' 
  palette:
    - scheme: slate
      primary: deep purple
      accent: deep purple

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.snippets
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - admonition

plugins:
  - search:
      lang: en