site_name: Frequently Asked Questions
site_url: https://tab1-web.github.io/faq/
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Getting Started:
    - 'Welcome': General/Website/website.md
    - 'Servers': General/Servers/servers.md
    - 'Cosmetics Info': General/Cosmetics/cosmetics-general.md
    - 'Cosmetics Preview':
      - 'Hats': General/Cosmetics/Hats/hats.md
      - 'Suits': General/Cosmetics/Suits/suits.md
      - 'Cloaks': General/Cosmetics/Cloaks/cloaks.md
      - 'Agathions': General/Cosmetics/Agathions/agathions.md
  - Help & Support:
    - 'Report Dual-box/Bot': General/Security/UserSafety/report.md
    - 'How to open a ticket?': General/Security/UserSafety/ticket.md
    - 'User Safety': General/Security/UserSafety/security.md
    - 'Rules': General/Security/UserSafety/rules.md
    - 'Troubleshoot':
      - 'In-Game Issues': General/TechnicalIssues/inside.md
      - 'Out-of-Game Issues': General/TechnicalIssues/outside.md
  - Gameplay:
    - 'General': 
      - 'Game': Game/General/game.md
      - 'PK System': Game/General/pk.md
    - 'Progression':
      - 'Subclasses': Game/subclasses.md
      - 'Noblesse': Game/noblesse.md
      - 'Heroes & Olympiad': Game/heroes.md
    - 'L2Calc':
      - 'L2Calc': Game/L2Calc/l2calc.md

  - Signature:
    - 'Combat': Signature/Combat/signature-combat.md
    - 'Progression': Signature/Progression/signature-progression.md
    - 'Quests': Signature/Progression/Quests/signature-quests.md
theme:
  name: material
  
  favicon: images/favicon.png
  
  icon:
    logo: material/frequently-asked-questions

  

  font:
    text: Montserrat
    code: Red Hat Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.path
    - content.code.copy

  palette:

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: deep purple
      accent: purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: indigo
      accent: blue

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.snippets
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - admonition
  
plugins:
  - search
  - tags
