site_name: Frequently Asked Questions
site_url: https://tab1-web.github.io/faq/
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Getting Started:
    - Welcome: getting-started/welcome.md
    - Server Information: getting-started/servers.md
    - Account & Login Issues: getting-started/login-issues.md
  - Gameplay:
    - Core Mechanics: gameplay/core-mechanics.md
    - PvP System: gameplay/pvp-system.md
    - L2Calc: features/l2calcinterlude.md
    - Macro: gameplay/macro.md
    - Character Progression:
      - Subclasses: gameplay/progression/subclasses.md
      - Noblesse: gameplay/progression/noblesse.md
      - Heroes & Olympiad: gameplay/progression/heroes.md
  - Cosmetics:
    - Overview: cosmetics/overview.md
    - Hats: cosmetics/hats.md
    - Suits: cosmetics/suits.md
    - Cloaks: cosmetics/cloaks.md
    - Agathions: cosmetics/agathions.md
  - Support:
    - Rules & Guidelines: support/rules.md
    - User Safety: support/user-safety.md
    - Reporting: support/reporting.md
    - Creating Tickets: support/tickets.md
    - Troubleshooting:
      - Game Issues: support/troubleshooting/game-issues.md
      - Technical Issues: support/troubleshooting/technical-issues.md
  - Eternal:
    - General: eternal/general.md
    - Maria: eternal/maria.md
    - Levelling: eternal/levelling.md
    - Missions: eternal/missions.md
    - Gear: eternal/gear.md
    - Classes: eternal/classes.md
    - Buffs: eternal/buffs.md
theme:
  name: material
  
  
  icon:
    logo: material/frequently-asked-questions

  

  font:
    text: Poppins   
    code: Red Hat Mono

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.path
    - content.code.copy
    - navigation.indexes
    
  palette:

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: deep purple
      accent: purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: indigo
      accent: blue

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      clickable_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.snippets
  - md_in_html
  - pymdownx.blocks.caption
  - tables
  - admonition
  
plugins:
  - search:
      lang: en
  - tags